---
{
  "kind": "pipeline",
  "name": "Kubernetes",
  "node_selector": { "drone": true },
  "platform": { "arch": "amd64", "os": "linux" },
  "steps":
    [
      {
        "commands":
          [
            "npm install prettier",
            "echo .pre-commit-config.yaml >> .prettierignore",
            'npx prettier --check "**/*.{ts,js,md,yaml,yml,sass,css,scss,html,htm}"',
          ],
        "image": "node:lts-buster",
        "name": "Prettier lint",
        "pull": "always",
      },
      {
        "commands":
          [
            "curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin",
            "golangci-lint run -v --timeout 10m",
          ],
        "image": "golang:1.16-buster",
        "name": "Go lint",
        "pull": "always",
      },
      {
        "commands": ["go test ./..."],
        "image": "golang:1.16-buster",
        "name": "Go test",
        "pull": "always",
      },
      {
        "commands":
          [
            "go get github.com/mitchellh/gox",
            'gox -osarch "!darwin/386" -output="dist/{{.Dir}}_{{.OS}}_{{.Arch}}"',
          ],
        "image": "golang:1.16-buster",
        "name": "Go build",
        "pull": "always",
      },
      {
        "environment": { "SSH_KEY": { "from_secret": "ssh_key" } },
        "image": "appleboy/drone-scp",
        "name": "Deploy with scp",
        "pull": "always",
        "settings":
          {
            "host": "core.terra.fap.no",
            "rm": true,
            "source": ["dist/*"],
            "strip_components": 1,
            "target": "/fastest/serve/builds/terraform-provider-opnsense",
            "username": "deploy",
          },
        "when": { "branch": ["master", "main"], "event": ["push"] },
      },
    ],
  "type": "kubernetes",
}
