pipeline:
  build:
      image: golang:1.12.1-stretch
      commands:
          - go get github.com/mitchellh/gox
          - gox -output="dist/{{.Dir}}_{{.OS}}_{{.Arch}}"
      when: 
        branch: master

  deploy:
      image: appleboy/drone-scp
      rm: true
      host: storage.terra.fap.no
      username: deploy
      target: /storage/nfs/k8s/builds/terraform-provider-opnsense
      source: 
        - dist/*
      strip_components: 1
      secrets: [ ssh_key ]

  notify:
    image: drillster/drone-email
    host: smtp.fap.no
    skip_verify: true
    port: 25
    from: drone@drone.fap.no
    recipients: [ kradalby@kradalby.no ]
    when:
      status: [ success, changed, failure ]


