---
kind: pipeline
type: kubernetes
name: default

node_selector:
  drone: "true"

steps:
  - name: lint
    image: golangci/golangci-lint:latest
    commands:
      - golangci-lint run -v --timeout 10m

  - name: build
    image: golang:1.14.2-stretch
    commands:
      - go get github.com/mitchellh/gox
      - gox -output="dist/{{.Dir}}_{{.OS}}_{{.Arch}}"

  - name: deploy
    pull: always
    image: appleboy/drone-scp
    settings:
      host: storage.terra.fap.no
      rm: true
      source:
        - dist/*
      strip_components: 1
      target: /storage/nfs/k8s/builds/terraform-provider-opnsense
      username: deploy
    environment:
      SSH_KEY:
        from_secret: ssh_key
    when:
      branch:
        - master
      event:
        - push

---
kind: secret
name: ssh_key
get:
  path: ssh
  name: deploy
