linters-settings:
  errcheck:
    exclude: .errcheck_ignore.txt

linters:
  fast: false
  presets:
    - style
    - bugs
    - unused
    - format
  disable:
    - interfacer
    - gomnd
    - godox
    - funlen
